"use strict";
const {test}=require("node:test"),assert=require("node:assert/strict");
const {makeDraft}=require("./scaffold-weekly.js"),{merge}=require("./ingest-candidates.js");
const original=()=>({...makeDraft("2026-10-09").data,items:[{candidate_id:"W2026-10-09-A01",source_url:"https://example.org/existing",source_title:"Existing",decision:"hold",source_checked:false}],screening_summary:{candidate_count:1,ready_to_publish:0,verified_for_publication:0}});
const batch={batch_id:"2026-10-09-policies-1",searched_on:"2026-10-09",sources:[{group:"official-policy",query:"K12 AI education",status:"ok"}],candidates:[{source_url:"https://example.org/NEW?tracking=1",source_title:"New",source_locator:"page",source_publication_date:"2026-10-09",event_key:"policy-a"},{source_url:"https://example.org/new#copy",source_title:"Repeated",source_locator:"page",source_publication_date:"2026-10-09"},{source_url:"https://example.org/old",source_title:"Old",source_locator:"page",source_publication_date:"2026-09-23",doi:"10.1234/test"}]};
test("cumulative import de-duplicates and preserves existing hold",()=>{const r=merge(original(),batch);assert.equal(r.added.length,2);assert.equal(r.duplicates.length,1);assert.equal(r.worksheet.items[0].source_checked,false);assert.equal(r.worksheet.items[1].decision,"hold");assert.match(r.worksheet.items[2].screening_note,/backfill/);assert.equal(r.worksheet.screening_summary.candidate_count,3);assert.equal(r.worksheet.search_runs[0].sources[0].group,"official-policy")});
test("duplicate batch rejected and original untouched",()=>{const first=merge(original(),batch).worksheet;const before=JSON.stringify(first);assert.throws(()=>merge(first,batch),/already ingested/);assert.equal(JSON.stringify(first),before)});
test("invalid coverage and source date fail closed",()=>{assert.throws(()=>merge(original(),{...batch,sources:[]}),/source-coverage/);assert.throws(()=>merge(original(),{...batch,candidates:[{source_url:"https://example.org/b",source_title:"bad",source_locator:"x",source_publication_date:"2026-02-30"}]}),/calendar/)});
test("event key merges across different language URLs",()=>{const a=merge(original(),batch).worksheet;const x=merge(a,{...batch,batch_id:"2026-10-10-policies-2",searched_on:"2026-10-10",candidates:[{source_url:"https://another.example/news",source_title:"Translation",source_locator:"text",event_key:"policy-a"}]});assert.equal(x.added.length,0);assert.equal(x.duplicates.length,1)});
